services:

  # ==========================
  # PostgreSQL
  # ==========================
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ==========================
  # Spring Boot
  # ==========================
  spring-app:
    build: ./spring-app
    container_name: spring-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  # ==========================
  # Prometheus
  # ==========================
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - spring-app
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  # ==========================
  # Grafana
  # ==========================
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  pgdata:
  prometheus-data:
  grafana-data:

